booksite/booksite/urls.py
from django.conf.urls import *
from django.contrib import admin
#from django.views.generic.list import ListView
from django.views.generic import ListView, DetailView, TemplateView
from books.views import PublisherPageListView, books_by_publisher, \
BookByPublisherListView, BookListView
admin.autodiscover()

#models
from books.models import Publisher

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('booksite.views',
	url(r'^hello/$', 'hello'),
	url(r'^time/$', 'current_datetime'),
	url(r'^another-time-page/$', 'current_datetime'),
	url(r'^time/plus/(\d{1,2})/$', 'hours_ahead'),
	url(r'^hours/plus/(?P<offset>\d{1,2})/$', 'hours_ahead'),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^display-meta/','display_meta'),
	url(r'^image/', 'my_image'),
)

urlpatterns += patterns('books.views', 
	url(r'^search-form/$', 'search_form'),
	url(r'^search/$', 'search'),
	url(r'^about/$', TemplateView.as_view(template_name='about.html')),
	url(r'^about/(\w+)/$', 'about_pages'),
)

urlpatterns += patterns('contact.views',
	url(r'^contact-form/$', 'contact'),
)

publisher_info= {
	'queryset': Publisher.objects.all(),
	'template_name': 'publisher_list.html',
	'template_object_name': 'publisher'
}

def get_books():
	return Book.objects.all()

publisher_info1= {
	'queryset': Publisher.objects.all(),
	'template_object_name': 'publisher',
	'extra_context': {'book_list': get_books}
}

urlpatterns += patterns('books.views', 
	url(r'^publishers1/$', ListView.as_view(),publisher_info),
	url(r'^publishers/$', ListView.as_view(model=Publisher,)),
	url(r'^publishers2/$', ListView.as_view(
		queryset = Publisher.objects.all(),
		template_name = 'publisher_list.html')),
	url(r'^publishers4/$',PublisherPageListView.as_view(
		template_name='publisher_list.html')),
	url(r'^books/(\w+)/$', books_by_publisher),
	url(r'^books1/(\w+)/$', BookByPublisherListView.as_view(), name='books_by_publisher.html'),
	url(r'^datebooks/$', BookListView.as_view()),
)

booksite/contact/models.py
from django.db import models
from books.models import Publisher


class Contact_Information(models.Model):
	contact = models.AutoField(primary_key=True)
	publisher = models.ForeignKey(Publisher, related_name='publisher_contact')
	email = models.CharField(max_length=30)
	phone = models.CharField(max_length=10)

booksite/contact/forms.py
from django import forms

class ContactForm(forms.Form):
	subject = forms.CharField(max_length=100)
	email = forms.EmailField(required = False,
	label="Your email address")
	message = forms.CharField(widget=forms.Textarea)
	
	def clean_message(self):
		message = self.cleaned_data['message']
		num_words = len(message.split())
		if num_words < 4:
			raise forms.ValidationError("Not enough words!")
		return(message)

booksite/contact/views.py
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render
from contact.forms import ContactForm

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            send_mail(
                cd['subject'],
                cd['message'],
                cd.get('email', 'noreply@example.com'),
                ['siteowner@example.com'],
            )
            return HttpResponseRedirect('/contact/thanks/')
    else:
        form = ContactForm(
            initial={'subject': 'I love your site!'}
        )
    return(render(request, 'contact_form.html', {'form': form}))

booksite/templates/contact/contact_form.html
<html>
<head>
    <title>Contact us</title>
</head>
<body>
    <h1>Contact us</h1>

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" method="post">
        <div class="field">
            {{ form.subject.errors }}
            <label for="id_subject">Subject:</label>
            {{ form.subject }}
        </div>
        <div class="field">
            {{ form.email.errors }}
            <label for="id_email">Your e-mail address:</label>
            {{ form.email }}
        </div>
        <div class="field">
            {{ form.message.errors }}
            <label for="id_message">Message:</label>
            {{ form.message }}
        </div>
        <input type="submit" value="Submit">
    </form>
</body>
</html>

<!--<html>
<head>
    <title>Contact us</title>
</head>
<body>
    <h1>Contact us</h1>

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" method="post">
        <table>
            {{ form.as_table }}
        </table>
        {% csrf_token %}
        <input type="submit" value="Submit">
    </form>
</body>
</html>
-->